### ISSUE TITLE
Understanding replication

### ISSUE THREAD

**Issue by nicola** [marcelklehr/gulf#22]
I have two divs "doc" and "replica".

"doc" and "replica" are like two documents on two different servers,
two different users should be able to edit either and they should be in sync.

What I do is the following:
- Create docA which is a slave
- Create docB which is a master
- Create docBReplica that is also a master
- I pipe (duplex) docA and docB, docA and docBReplica

However, when I write in one div, I don't have the replica copying instantaneously my changes.

Any hint on that?

```javascript
var bindEditor = require('gulf-contenteditable')
var domOT = require('dom-ot')
var gulf = require('gulf')

document.addEventListener('DOMContentLoaded', function () {
  var editable = document.querySelector('#doc[contenteditable]')
  var editableReplica = document.querySelector('#replica')
  var docB = bindEditor(editable)
  var docBReplica = bindEditor(editableReplica)

  gulf.Document.create(
    new gulf.MemoryAdapter,
    domOT,
    document.createElement('div'),
    function (er, docA) {
      var linkA = docA.slaveLink()

      var linkB = docB.masterLink()
      var linkBReplica = docBReplica.masterLink()

      linkA.pipe(linkB).pipe(linkA)
      linkA.pipe(linkBReplica).pipe(linkA)

      linkB.pipe(linkA).pipe(linkB)
      linkBReplica.pipe(linkA).pipe(linkBReplica)

    })
})
```

**Comment by marcelklehr** [comment]
You need *two* slave links from docA, one for each slave document.

```js
var bindEditor = require('gulf-contenteditable')
var domOT = require('dom-ot')
var gulf = require('gulf')

document.addEventListener('DOMContentLoaded', function () {
  var editable = document.querySelector('#doc[contenteditable]')
  var editableReplica = document.querySelector('#replica')
  var docB = bindEditor(editable)
  var docBReplica = bindEditor(editableReplica)

  gulf.Document.create(
    new gulf.MemoryAdapter,
    domOT,
    document.createElement('div'),
    function (er, docA) {
      var linkA = docA.slaveLink()

      var linkB = docB.masterLink()
      var linkBReplica = docBReplica.masterLink()

      linkB.pipe(docA.slaveLink()).pipe(linkB)
      linkBReplica.pipe(docA.slaveLink()).pipe(linkBReplica)

    })
})
```

**Comment by nicola** [comment]
Of course, I cannot reuse the same slave link!

It works, however, the cursor goes from the end of the sentence to the beginning,
any reason that is happening?

**Comment by marcelklehr** [comment]
That's probably because the document is reset, because of an error. :/ I'm going to set up a requirebin for documentation/demonstration purposes anyway, in a moment...

**Comment by nicola** [comment]
Thanks! Keep me posted!

**Comment by marcelklehr** [comment]
Okay, so requirebin had problems with dom-ot, I guess, so I did it without that. See https://gist.github.com/marcelklehr/0430be7e3fb45a83189b

**Comment by marcelklehr** [comment]
I've never tried it with two contenteditables on the same page. It's probably the selection retention of one document kicking the selection of the other.

**Comment by marcelklehr** [comment]
Yep, that was the problem. Fixed, now :)
