### ISSUE TITLE
Add a remoteStorage storage adapter

### ISSUE THREAD

**Issue by marcelklehr** [marcelklehr/gulf#26]
https://remotestorage.io/

**Comment by marcelklehr** [comment]
depends on #25

**Comment by derhuerst** [comment]
Consider [`abstract-blob-store`](https://github.com/maxogden/abstract-blob-store#abstract-blob-store).

**Comment by marcelklehr** [comment]
@derhuerst Good idea! See https://github.com/marcelklehr/gulf/issues/31
