### ISSUE TITLE
stop logging to stdout

### ISSUE THREAD

**Issue by derhuerst** [marcelklehr/gulf#28]
I've been using `gulf` for a few hours now and it has been a pleasant experience (with minor exceptions on the documentation side).

I use [`blessed`](https://github.com/chjj/blessed) & [`editor-widget`](https://github.com/slap-editor/editor-widget#readme) to render an editor. Because `blessed` controls `process.stdout` & `process.stderr`, `gulf` writing to it messes everything up.

**No library should ever write to `process.stdout` (and, if you will, `process.stderr` as well)!** For selective logging, there are modules like [`debug`](https://github.com/visionmedia/debug).

I'd be happy to submit a PR that removes the logging or, if you wish, puts `debug` in place.

**Comment by marcelklehr** [comment]
Yes, that has been on my to-do list. You're welcome to send a pr replacing stdout logging with debug or similar, the solution should work in the browser, too, though.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by derhuerst** [comment]
Will submit a PR.

BTW: The test do not pass on `master`. They fail with "`expect` is not a function".

**Comment by marcelklehr** [comment]
Thank you! Travis seems to be able to run the tests just fine. I suspect that you have gulf installed as a dependency (ie. in node_modules). Running the tests in there will not work. You will need to clone the repo somewhere else, install deps and devDependencies and try to run the tests again. For now it's fine though since travis shows a green light. I will test in the browser later today.

**Comment by derhuerst** [comment]
> Thank you! Travis seems to be able to run the tests just fine. I suspect that you have gulf installed as a dependency (ie. in node_modules). Running the tests in there will not work. You will need to clone the repo somewhere else, install deps and devDependencies and try to run the tests again. For now it's fine though since travis shows a green light. I will test in the browser later today.

I did.

```js
git clone derhuerst/gulf
cd gulf
npm install
npm test
```

**Comment by marcelklehr** [comment]
Weird. Which node version are do you use?

**Comment by derhuerst** [comment]
Latest from Homebrew, so `v6.5.0`.
