### ISSUE TITLE
No indication of which module ws came from in the example

### ISSUE THREAD

**Issue by 619** [marcelklehr/gulf#40]
In the usage examples, what exactly is "ws"? Did it come from websockets, the npm package ws, or nodejs net?

**Comment by marcelklehr** [comment]
The example is not a working code snippet. It leaves it up to the viewers imagination where ws comes from. The point being that gulf is not tied to any specific transport layer.

**Comment by 619** [comment]
Well, it would be nice if you explicitly stated that. I had assumed that you just forgot to import the package or something. Is it ~~possible~~ probable for me to implement your warp example (https://github.com/marcelklehr/warp) with the editable area being the entire html document, in an environment other than localhost?

**Comment by marcelklehr** [comment]
> Is it possible probable for me to implement your warp example (https://github.com/marcelklehr/warp) with the editable area being the entire html document, in an environment other than localhost?

That's technically possible, I think, yes. I wouldn't feel comfortable recommending the use of gulp in its current state, though. The JavaScript landscape has moved a lot since then. see #39 ;)
